name: badges
on:
  push:
    branches:
      - main
      - master

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup
      - name: create coverage badge
        run: make test coverage-badge
      - name: commit and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update badges"
          git push --force origin gh-pages