name: setup
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.13'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: install dependencies
        run:
          pip install uv
          make setup